name: ODailyQuests
version: 1.0
main: com.odailyquests.ODailyQuests
api-version: 1.21
commands:
  daily:
    description: Open the daily quest GUI
    usage: /daily quest
  questcomplete:
    description: Complete a manual quest
    usage: /questcomplete <player>
